### PR TITLE
new setting for disabling unique indexes

### PR DESCRIPTION
**Pull request by iiome**
Hi, I have added a setting to let the developper choose if he want to disable the unique index over the field. This  use case happens when you have another field like version and you to keep several documents with the same number.

### CODE REVIEW

**Comment by chevex** [comment]
Thanks!

**Comment by chevex** [comment]
I will publish a new version of the npm module later today :)

**Comment by iiome** [comment]
thanks! looking forward to it.

**Comment by akademy** [comment]
Any chance of getting the package published? I'd really like this unique field option ;)

**Pull request merged**
